import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Grid from '@mui/material/Grid'
import Input from '@mui/material/Input'
import InputLabel from '@mui/material/InputLabel'
import FormControl from '@mui/material/FormControl'

import {useState} from 'react'



export default function Home() {
  const [url, setUrl] = useState('')

  const validateUrl = ()=>{
    var r = new RegExp(/^(ftp|http|https):\/\/[^ "]+$/);
    return (r.test(url))
  }

  const proxy = ()=>{
    const base = 'http://amercorsproxy.pythonanywhere.com/proxy?url='
    var newUrl = url.replaceAll('?', '&')
    return (base+newUrl)
  }

  return (
    <div>
      <Head>
        <title>Create API Proxy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Grid container style={{marginTop: '100px'}} justifyContent="space-around">
        <Grid item xs={10} style={{margin: '0 auto'}}>
          <h1 style={{textAlign: 'center'}}>Enter An API End Point Below to Give You A Proxy</h1>
        </Grid>
        <Grid item xs={10} md={8}>
          <FormControl variant="standard" style={{margin: '40px auto', width: '100%'}}>
            <InputLabel htmlFor="component-simple">Your API Endpoint</InputLabel>
            <Input id="component-simple" value={url} onChange={(e)=>{setUrl(e.target.value)}} />
          </FormControl>
        </Grid>
        <Grid item xs={10}>
          {validateUrl() && <div>
                              <h4 style={{textAlign: 'center'}}>Here&apos;s your proxy end point:</h4>
                              <h5 style={{textAlign: 'center'}}>{proxy()}</h5>
                            </div>}
          {!validateUrl() && <h5 style={{textAlign: 'center'}}>Enter A Valid URL</h5>}
        </Grid>
        <Grid item xs={10} style={{marginTop: '30px'}}>
          <h5 style={{textAlign: 'center'}}>Note: For this to work, your api should by whitelisted here:</h5>
          <h5 style={{textAlign: 'center', color: 'blue', cursor: 'pointer'}} onClick={()=>{window.open('https://www.pythonanywhere.com/whitelist/')}}>https://www.pythonanywhere.com/whitelist/</h5>
        </Grid>
      </Grid>
      
      
      
      <Footer style={{position: 'absolute', bottom: '0'}}/>
      
    </div>
  )
}
